C4 MNIST HW Part 3: load PCA model, and try more different images on different classification

Data Source: https://www.kaggle.com/c/state-farm-distracted-driver-detection

State Farm Distracted Driver Images

10 different labels/categories for each images

Each color image is 640*480 22424 images in training dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
# PIL => Python Imaging Library
from PIL import Image

In [7]:
import os

In [8]:
from sklearn.model_selection import train_test_split

In [2]:
def readcsvfile(filename):
    file_open=open(filename,'r')
    lines_data=[]
    for line in iter(file_open):
        line=line.rstrip()
        lines_data.append(line.split(','))
    return lines_data

In [3]:
def hasThisFile(filename):
    return os.path.isfile(filename)

In [14]:
def getJPGfileData(filename):
    if hasThisFile(filename):
        img=Image.open(filename)
        img=img.convert('L')
        return list(img.getdata())

In [4]:
dtsinfo=readcsvfile('sfdd_train_data_rest_fv1.csv')

In [9]:
train1, train2 = train_test_split(dtsinfo, test_size=0.95)

In [10]:
trainImgFileDir='../dataSetImage/stateFarm_distractedDriver_all/imgs/train/'

In [11]:
imgsz=640*480
trainsz=len(train1)

In [12]:
XTrain1NP=np.empty((trainsz,imgsz),dtype=np.int8)

In [15]:
i=0
for itm in train1:
    XTrain1NP[i].flat[:]=getJPGfileData(trainImgFileDir+itm[1]+'/'+itm[2])
    i+=1

In [17]:
# load the model from disk
import pickle
filename = 'sfdd_pca_fv1.pkl'
loaded_pca_model = pickle.load(open(filename, 'rb'))

In [18]:
Ytrain1=[]

In [19]:
for itm in train1:
    Ytrain1.append(int(itm[1][1]))

In [20]:
Ytrain1NP=np.array(Ytrain1)

In [21]:
principalComponents = loaded_pca_model.transform(XTrain1NP)

In [24]:
train3, train4 = train_test_split(train2, test_size=0.95)
XTrain3NP=np.empty((len(train3),imgsz),dtype=np.int8)
i=0
for itm in train3:
    XTrain3NP[i].flat[:]=getJPGfileData(trainImgFileDir+itm[1]+'/'+itm[2])
    i+=1

In [30]:
fif=open('sfdd_train_data_rest_fv2.csv','w')
for x in train4:
    fif.write(','.join(x)+'\n')
fif.close() 

In [25]:
pcts2 = loaded_pca_model.transform(XTrain3NP)

In [26]:
Ytrain3=[]
for itm in train3:
    Ytrain3.append(int(itm[1][1]))
Ytrain3NP=np.array(Ytrain3)

In [28]:
import sklearn.metrics as metrics

In [29]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(principalComponents,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(pcts2)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
             precision    recall  f1-score   support

          0       0.38      0.49      0.42       101
          1       0.43      0.39      0.41       109
          2       0.38      0.35      0.37       102
          3       0.37      0.46      0.41       107
          4       0.44      0.37      0.40        92
          5       0.50      0.45      0.47        94
          6       0.37      0.39      0.38        93
          7       0.31      0.26      0.28        69
          8       0.26      0.22      0.24        72
          9       0.31      0.34      0.32        74

avg / total       0.38      0.38      0.38       913

[[49  6  4 

In [31]:
# Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(principalComponents,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(pcts2)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB(priors=None)
             precision    recall  f1-score   support

          0       0.41      0.46      0.43       101
          1       0.45      0.38      0.41       109
          2       0.28      0.19      0.22       102
          3       0.26      0.24      0.25       107
          4       0.52      0.40      0.45        92
          5       0.47      0.33      0.39        94
          6       0.30      0.52      0.38        93
          7       0.28      0.39      0.33        69
          8       0.23      0.32      0.27        72
          9       0.41      0.27      0.33        74

avg / total       0.37      0.35      0.35       913

[[46  9  7  9  3  1  8  5  5  8]
 [ 3 41  9 14  0  1 16 14 11  0]
 [ 3 11 19 11  2  2 21 14 16  3]
 [19  8  8 26 17  6  8  3  7  5]
 [ 5  5  5 11 37  6  7  6  7  3]
 [14  5  1  9  4 31 14  7  8  1]
 [ 2  9  6  5  1  4 48  7 10  1]
 [ 5  2  3  6  1  1 13 27  8  3]
 [ 6  1  5  1  3 10 12  6 23  5]
 [ 8  0  4  9  3  4 14  7  5 20]]


In [32]:
# Knn- classification
# k-Nearest Neighbor Classification
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(principalComponents,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(pcts2)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

          0       0.56      0.78      0.66       101
          1       0.60      0.75      0.67       109
          2       0.53      0.69      0.60       102
          3       0.61      0.62      0.61       107
          4       0.64      0.59      0.61        92
          5       0.80      0.64      0.71        94
          6       0.67      0.73      0.70        93
          7       0.92      0.64      0.75        69
          8       0.86      0.50      0.63        72
          9       0.71      0.43      0.54        74

avg / total       0.67      0.65      0.65       913

[[79  7  1  5  2  0  4  0  1  2]
 [ 8 82 11  3  2  0  0  1  0  2]
 [ 1 14 70  3  1  2  8  0  2  1]
 [ 9  5 11 66 11  3  1  0  0  1]
 [11  0  2 20 54  1  2  0  0  2]
 [13  6  4  2  4 60  4  0  0  1]

In [33]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver = 'lbfgs',random_state=10)
model.fit(principalComponents,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(pcts2)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=10, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False)
             precision    recall  f1-score   support

          0       0.57      0.70      0.63       101
          1       0.50      0.47      0.49       109
          2       0.56      0.52      0.54       102
          3       0.69      0.61      0.65       107
          4       0.49      0.51      0.50        92
          5       0.66      0.50      0.57        94
          6       0.49      0.48      0.49        93
          7       0.60      0.65      0.63        69
          8       0.53      0.57      0.55        72
          9       0.47      0.55      0.51        74

avg / total       0.56      0.55      0.55       913

[[71  9  2  3  2  1  3  2  1  7]
 [ 9 51 17  1  7  1  6  4  5  8]
 [ 7  8 53  2  3  3 14  4  6  2]
 [1