C4 MNIST HW Part 4: Try different classification without PCA

Data Source: https://www.kaggle.com/c/state-farm-distracted-driver-detection

State Farm Distracted Driver Images

10 different labels/categories for each images

Each color image is 640*480 22424 images in training dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# PIL => Python Imaging Library
from PIL import Image

In [13]:
import os

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
def readcsvfile(filename):
    file_open=open(filename,'r')
    lines_data=[]
    for line in iter(file_open):
        line=line.rstrip()
        lines_data.append(line.split(','))
    return lines_data

In [5]:
def hasThisFile(filename):
    return os.path.isfile(filename)

In [6]:
def getJPGfileData(filename):
    if hasThisFile(filename):
        img=Image.open(filename)
        img=img.convert('L')
        return list(img.getdata())

In [7]:
dtsinfo=readcsvfile('sfdd_train_data_rest_fv2.csv')

In [8]:
train1, train2 = train_test_split(dtsinfo, test_size=0.95)

In [9]:
trainImgFileDir='../dataSetImage/stateFarm_distractedDriver_all/imgs/train/'

In [10]:
imgsz=640*480
trainsz=len(train1)

In [11]:
XTrain1NP=np.empty((trainsz,imgsz),dtype=np.int8)

In [14]:
i=0
for itm in train1:
    XTrain1NP[i].flat[:]=getJPGfileData(trainImgFileDir+itm[1]+'/'+itm[2])
    i+=1

In [15]:
Ytrain1=[]

In [16]:
for itm in train1:
    Ytrain1.append(int(itm[1][1]))

In [17]:
Ytrain1NP=np.array(Ytrain1)

In [18]:
train3, train4 = train_test_split(train2, test_size=0.95)
XTrain3NP=np.empty((len(train3),imgsz),dtype=np.int8)
i=0
for itm in train3:
    XTrain3NP[i].flat[:]=getJPGfileData(trainImgFileDir+itm[1]+'/'+itm[2])
    i+=1

In [19]:
fif=open('sfdd_train_data_rest_fv3.csv','w')
for x in train4:
    fif.write(','.join(x)+'\n')
fif.close() 

In [20]:
Ytrain3=[]
for itm in train3:
    Ytrain3.append(int(itm[1][1]))
Ytrain3NP=np.array(Ytrain3)

In [21]:
import sklearn.metrics as metrics

In [22]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(XTrain1NP,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(XTrain3NP)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
             precision    recall  f1-score   support

          0       0.51      0.46      0.48        94
          1       0.38      0.43      0.41        81
          2       0.43      0.44      0.43        91
          3       0.30      0.35      0.32        72
          4       0.38      0.35      0.36        80
          5       0.66      0.56      0.60       102
          6       0.38      0.39      0.38        84
          7       0.52      0.58      0.55        78
          8       0.53      0.47      0.50        60
          9       0.34      0.35      0.35        82

avg / total       0.45      0.44      0.44       824

[[43  3 14 

In [23]:
# Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(XTrain1NP,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(XTrain3NP)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB(priors=None)
             precision    recall  f1-score   support

          0       0.44      0.50      0.47        94
          1       0.27      0.25      0.26        81
          2       0.19      0.19      0.19        91
          3       0.17      0.36      0.23        72
          4       0.35      0.33      0.34        80
          5       0.57      0.48      0.52       102
          6       0.28      0.23      0.25        84
          7       0.56      0.47      0.51        78
          8       0.46      0.38      0.42        60
          9       0.57      0.37      0.44        82

avg / total       0.39      0.36      0.37       824

[[47  0  7 17  5  8  5  1  1  3]
 [13 20  9 18  1  4  9  3  2  2]
 [ 7  9 17 20  2  5 12 10  4  5]
 [ 6  2  9 26 18  5  0  1  3  2]
 [13  1 10 20 26  1  2  4  0  3]
 [ 3  3  7 24  5 49  6  1  4  0]
 [ 4 16 12 14  8  5 19  1  4  1]
 [ 1  9 11  4  4  1  6 37  3  2]
 [ 4 10  2  4  2  3  2  5 23  5]
 [ 9  4  5  9  3  5  8  3  6 30]]


In [24]:
# Knn- classification
# k-Nearest Neighbor Classification
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(XTrain1NP,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(XTrain3NP)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
             precision    recall  f1-score   support

          0       0.56      0.71      0.63        94
          1       0.47      0.79      0.59        81
          2       0.45      0.58      0.51        91
          3       0.38      0.44      0.41        72
          4       0.70      0.57      0.63        80
          5       0.82      0.58      0.68       102
          6       0.49      0.54      0.51        84
          7       0.79      0.54      0.64        78
          8       0.57      0.40      0.47        60
          9       0.93      0.49      0.64        82

avg / total       0.62      0.57      0.58       824

[[67  9  8  6  1  0  3  0  0  0]
 [ 6 64  7  2  0  0  1  1  0  0]
 [ 5 18 53  6  0  1  7  0  1  0]
 [ 5  9 11 32 13  0  1  0  1  0]
 [ 6  3  5 13 46  0  3  1  3  0]
 [10  6  5 11  1 59 10  0  0  0]

In [25]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver = 'lbfgs',random_state=10)
model.fit(XTrain1NP,Ytrain1NP)
print(model)
# make predictions
expected = Ytrain3NP
predicted = model.predict(XTrain3NP)
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=10, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False)
             precision    recall  f1-score   support

          0       0.74      0.78      0.76        94
          1       0.63      0.88      0.74        81
          2       0.85      0.76      0.80        91
          3       0.74      0.83      0.78        72
          4       0.77      0.79      0.78        80
          5       0.87      0.80      0.84       102
          6       0.81      0.70      0.75        84
          7       0.85      0.87      0.86        78
          8       0.83      0.72      0.77        60
          9       0.87      0.74      0.80        82

avg / total       0.80      0.79      0.79       824

[[73  9  2  3  3  1  1  1  0  1]
 [ 1 71  2  2  0  0  4  1  0  0]
 [ 0 10 69  3  0  0  3  1  5  0]
 [ 